# .github/workflows/image_build.yml
name: Image CI Build

on:
  pull_request:
    branches: ["main"]

jobs:
  image_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build docker image
        id: build-image
        env:
          BD_MONGO_URL: ${{ secrets.BD_MONGO_URL }}
        run: |
          docker build -t my-app:latest --build-arg BD_MONGO_URL=$BD_MONGO_URL .
          echo "Docker image built successfully"
