name: Build Docker Image and Display in Console

on:
  push:
    branches:
      - main

jobs:
  build-and-display:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Preparar el sistema para Docker
      - name: Remove conflicting packages
        run: |
          sudo apt-get remove -y containerd containerd.io docker docker-engine docker.io || true
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update

      # Paso 3: Instalar Docker
      - name: Install Docker
        run: |
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          docker --version

      # Paso 4: Construir la imagen Docker
      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      # Paso 5: Listar imágenes Docker
      - name: List Docker Images
        run: |
          echo "Mostrando imágenes Docker disponibles:"
          docker images
