name: Build and Deploy Docker Image to EC2

on:
  push:
    branches:
      - feature/ec2_v2

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: private-api-backend
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      EC2_URL: ${{ secrets.EC2_URL }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
          EC2_URL: $EC2_URL

      - name: Verify remote directory exists (and create it if it doesn't)
        run: |
          ssh -o StrictHostKeyChecking=no -i $EC2_SSH_PRIVATE_KEY $EC2_USERNAME@$EC2_URL "mkdir -p /home/ubuntu/docker_images"

      - name: Copy code to EC2 instance
        run: |
          scp -o StrictHostKeyChecking=no -i $EC2_SSH_PRIVATE_KEY -r ./ $EC2_USERNAME@$EC2_URL:/home/ubuntu/docker_images
