name: Build and Deploy Docker Image to EC2

on:
  push:
    branches:
      - feature/ec2_v2

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: private-api-backend
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      EC2_URL: ${{ secrets.EC2_URL }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}

    steps:
      - name: Setup SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
          EC2_URL: $EC2_URL
      # then you can run commands/scripts directly on the EC2 instance e.g.:
      - name: Create a new file on the EC2 instance with "hello-world"
        run: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_URL "echo "hello-world" >> new_file.txt"
